In [1]:
import cv2
import numpy as np


In [3]:
#membaca pixel image (blue, green, red)
image = cv2.imread("Dataset/Seledri/001.jpg")
print(image)

[[[131 133 127]
  [131 133 127]
  [131 133 127]
  ...
  [152 165 157]
  [152 165 157]
  [152 165 157]]

 [[131 133 127]
  [131 133 127]
  [131 133 127]
  ...
  [152 165 157]
  [152 165 157]
  [152 165 157]]

 [[131 133 127]
  [131 133 127]
  [131 133 127]
  ...
  [152 165 157]
  [152 165 157]
  [152 165 157]]

 ...

 [[ 93  95  89]
  [ 93  95  89]
  [ 94  96  90]
  ...
  [126 134 127]
  [126 134 127]
  [126 134 127]]

 [[ 93  95  89]
  [ 93  95  89]
  [ 94  96  90]
  ...
  [126 134 127]
  [126 134 127]
  [126 134 127]]

 [[ 93  95  89]
  [ 93  95  89]
  [ 94  96  90]
  ...
  [126 134 127]
  [126 134 127]
  [126 134 127]]]


In [4]:
#adjust image contrast 
r = 400/image.shape[1]
dim = (400,int(image.shape[0]*r))
im_resized = cv2.resize(image, dim)

im_adjusted = cv2.addWeighted(im_resized, 1.5, np.zeros(im_resized.shape, im_resized.dtype), 0, -100)
im_edges = cv2.Canny(im_resized, 100, 200)

cv2.imshow('original image', im_resized)
cv2.imshow('adjusted image', im_adjusted)
cv2.imshow('Detected Edges', im_edges)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
#ubah se-folder
import glob

imdir = 'Dataset/Seledri/'
ext = ['jpg']

files = []
[files.extend(glob.glob(imdir + '*.' + e)) for e in ext]

images = [cv2.imread(file) for file in files]

i = 1
for img in images:
    im_adjusted = cv2.addWeighted(img, 1.5, np.zeros(img.shape, img.dtype), 0, -100)
    im_name = "Dataset/Seledri/Seledri_Edit/" +  str(i) + ".jpg"
    cv2.imwrite(im_name, im_adjusted)
    i += 1